export const INIT = "INIT";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const SPREADSHEET_REQ_START = "SPREADSHEET_REQ_START";
export const SPREADSHEET_REQ_SUCCESS = "SPREADSHEET_REQ_SUCCESS";
export const LIST_REQ_START = "LIST_REQ_START";
export const LIST_REQ_SUCCESS = "LIST_REQ_SUCCESS";
